version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: example

  app:
    build: .
#    volumes:
#      - ./src:/usr/local/tomcat/webapps
    ports:
      - "8082:8080"
    environment:
      APP_NAME: 'Mlpk'
      APP_CLASS: 'com.mlpk'
      DB_HOST: "db"
